// <auto-generated />
namespace CapStoneApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatepropsofclient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatepropsofclient));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070701015_update props of client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
