// <auto-generated />
namespace CapStone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newpropsoncandidate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newpropsoncandidate));
        
        string IMigrationMetadata.Id
        {
            get { return "202002041338590_new props on candidate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
